// Generated by CoffeeScript 1.3.3
(function() {
  var commander, oj, usage, _;

  _ = require('underscore');

  commander = require('commander');

  oj = require('./server');

  module.exports = function() {
    var options;
    commander.version(oj.version).usage('[options] <file> <dir> ...').option('-d, --debug', 'Turn on debug output (default: false)', false).option('-o, --output <dir>', 'Directory to output all files to (default: .)', process.cwd()).option('-r, --recurse', 'Recurse into directories (default: off)', false).option('-m, --modules <modules>', 'List of modules to include', []).option('-v, --verbose <level>', 'Turn on verbose level 0-3 (default: 1)', 1).option('-w, --watch', 'Turn on watch mode (default: off)', false).parse(process.argv);
    if (!_.isArray(commander.args) || commander.args.length === 0) {
      usage();
    }
    options = _.pick(commander, 'args', 'debug', 'output', 'recurse', 'modules', 'verbose', 'watch');
    oj.command(options);
  };

  usage = function(code) {
    if (code == null) {
      code = 0;
    }
    commander.help();
    return process.exit(code);
  };

}).call(this);
