// Generated by CoffeeScript 1.3.3
(function() {
  var fs, includer, path;

  path = require('path');

  fs = require('fs');

  module.exports = includer = function(directory) {
    console.log("includer called with directory:", directory);
    return function(reference) {
      var file, fullPath;
      console.log("include called with reference:", reference);
      console.log("directory: ", directory);
      fullPath = path.resolve(reference);
      console.log("fullPath: ", fullPath);
      try {
        file = fs.readFileSync(fullPath, 'utf8');
        return console.log("file: ", file);
      } catch (e) {
        return console.log("e: ", e);
      }
    };
  };

}).call(this);
